version: '3.8'

services:
  webserver:
    user: "${USER_INFO}"
    hostname: test_project_please_ignore
    build:
      context: ./docker
      dockerfile: Dockerfile.webserver
    volumes:
      - ./vendor:/var/www/vendor
      - ./:/var/www
      - composer-cache:/root/.composer/cache
      - $HOME/.aws:/root/.aws
      - $HOME/.aws:/.aws
    command: sh -c "apache2-foreground"

volumes:
  composer-cache:
    external:
      name: dev-env_composer-cache

networks:
  default:
    external:
      name: mobials